# Generated by Django 3.2.5 on 2021-10-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_id', models.PositiveIntegerField()),
                ('reciver_id', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=300)),
                ('message_text', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
